version: '3.8'

services:
  speed-track-ui:
    build: .
    container_name: speed-track-ui
    restart: unless-stopped
    ports:
      - "8080:5000" # Erreichbar unter http://localhost:8080
    environment:
      - PORT=5000
      - CRON_SCHEDULE=0 * * * *
    volumes:
      - ./data:/app/data # Persistente Datenbank-Speicherung
